### ISSUE TITLE
Sidebar Auto Expanding

### ISSUE THREAD

**Issue by AlphaHasher** [aminought/firefox-second-sidebar#6] opened 2024-11-08 17:43 UTC
First I want to say that this is a fantastic idea that you came up with, and I am eager to give it a try.

However, I am running into an issue where as you can see in the video the sidebar is expanding. I installed both fx-autoconfig and put your files into the chrome folder as per the given installation instructions.

First time after installing I had this issue. The second time I tried with a brand new profile without migrating over my profile contents from my main profile and had the same issue.

https://github.com/user-attachments/assets/bd209f4b-dc19-45af-835f-c2034b4fbf3e

The blacked out boxes are for masking identifying user information

**Comment by mcortt** [comment] 2024-11-08 23:20
Same issue here

**Comment by ThinkSalat** [comment] 2024-11-09 01:34
Yes, I had the same issue as well! One a brand new ff install. resetting the cache again fixes it and moves the sidebar to the right

**Comment by aminought** [comment] 2024-11-09 02:17
Hi there, could you please send me the logs that are available in the [Browser Toolbox](https://firefox-source-docs.mozilla.org/devtools-user/browser_toolbox/index.html) console for me to view?

**Comment by mcortt** [comment] 2024-11-09 03:24
![Screenshot 2024-11-08 222251](https://github.com/user-attachments/assets/e7901459-a858-4d00-90bd-6052eefa025a)

**Comment by aminought** [comment] 2024-11-09 03:28
Thanks, now it's clear that something is wrong with loading the preferences. I'll try to reproduce it, your browser version will also help me a lot.

**Comment by mcortt** [comment] 2024-11-09 03:32
Running the latest version of Nightly. There was a bit more that was showing up the second time I ran it.
![Screenshot 2024-11-08 222950](https://github.com/user-attachments/assets/1bfd28b5-ba5b-4fa3-b805-98469c4220f2)

Version 	134.0a1
Build ID 	20241108155652

**Comment by mcortt** [comment] 2024-11-09 03:39
On a second view the other errors are for other things. Disregard, sorry.

**Comment by AlphaHasher** [comment] 2024-11-09 03:44
I am using the latest version as of now — 132.0.1 (64-bit)

**Comment by GunGunGun** [comment] 2024-11-09 16:04
> Hi there, could you please send me the logs that are available in the [Browser Toolbox](https://firefox-source-docs.mozilla.org/devtools-user/browser_toolbox/index.html) console for me to view?

I figured out why this issue happened, it was because by default there's no sites, it could be fixed by using `+` to add a random site, then restart and everything works fine.

This bug always happen to clean install:
![image](https://github.com/user-attachments/assets/ac0ac057-0080-40c4-99dd-d7c55adecb2f)

This is after getting fixed:
![image](https://github.com/user-attachments/assets/eef6b144-9467-40cc-859a-ecaf2030d3e3)

**Comment by mcortt** [comment] 2024-11-09 16:57
Awesome! Thanks for working on it!

**Comment by aminought** [comment] 2024-11-10 02:59
Fixed, sorry for that.

**Closed** 2024-11-10 03:00 UTC
Labels: bug
