### ISSUE TITLE
[Request] Option to enable mobile view for the web panel

### ISSUE THREAD

**Issue by emvaized** [aminought/firefox-second-sidebar#18] opened 2024-11-12 23:27 UTC
It would be awesome to have a setting for each web panel to apply mobile client to the page, because many pages open in their regular desktop view and doesn't adapt well to the small available width. 

Such option exists in the Floorp browser: 
![illustration](https://github.com/user-attachments/assets/a68c7250-9c12-406b-a1a7-2b9bcad2a76d)

**Comment by aminought** [comment] 2024-11-13 04:41
Duplicate of #12.

**Closed by aminought** 2024-11-13 04:41 UTC
Labels: duplicate
